services:
  jobhunter.worker:
    image: jobhunter.worker
    build:
      context: .
      dockerfile: JobHunter.Worker/Dockerfile
    depends_on:
      - playwright
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - microservices_net
  
  playwright:
    image: jacoblincool/playwright:firefox-server
    ports:
      - 53333:53333
    networks:
      - microservices_net

networks:
  microservices_net:
    driver: bridge
    name: microservices_net