START TRANSACTION;

CREATE TABLE "ProceedJobCheckpoints" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ServiceName" text NOT NULL,
    "Checkpoint" integer NOT NULL,
    "TimeStamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProceedJobCheckpoints" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Jobs_SourceId" ON "Jobs" ("SourceId");

COMMIT;

START TRANSACTION;

ALTER TABLE "Jobs" ADD "Keywords" jsonb NOT NULL DEFAULT '{}';

COMMIT;

